site_name: Solaris Wiki

docs_dir: wiki/

theme: readthedocs

extra_css: [
    _styles/style.css
]

repo_url: 'https://github.com/mike-eason/solaris'

nav:
  - Home: 'index.md'
  - 'Community Guidelines': 'communityGuidelines.md'
  - 'New Players': 'newPlayers.md'
  - Stars: 'stars.md'
  - Carriers: 'carriers.md'
  - Technology: 'technology.md'
  - Diplomacy: 'diplomacy.md'
  - 'AI Reputation': 'reputation.md'
  - Trade: 'trade.md'
  - Specialists: 'specialists.md'
  - Territories: 'territories.md'
  - Combat: 'combat.md'
  - 'Game Types': 'gameTypes.md'
  - 'Game Tick Events': 'gameTick.md'
  - Rankings: 'rankings.md'
  - Achievements: 'achievements.md'
  - 'Custom Galaxies': 'customGalaxies.md'
  - 'AFK Rules': 'afkRules.md'
  - 'Keyboard Shortcuts': 'keyboardShortcuts.md'